export interface Climareg {

    id:number,
    dia:string,
    imagen:string,
    grados:number,
    clima:string
}

export let ListaClimaVal:Array<Climareg>=[
    {
        id:1,
        dia:"Lunes",
        imagen:"1.png",
        grados:18,
        clima:"soleado"
    },
    {
        id:2,
        dia:"Martes",
        imagen:"3.jpg",
        grados:9,
        clima:"lluvioso"
    },
    {
        id:3,
        dia:"Miercoles",
        imagen:"2.jpg",
        grados:11,
        clima:"nublado"
    },
    {
        id:4,
        dia:"Jueves",
        imagen:"4.jpg",
        grados:7,
        clima:"tormenta"
    },
    {
        id:5,
        dia:"Viernes",
        imagen:"1.png",
        grados:22,
        clima:"soleado"
    },
    {
        id:6,
        dia:"Sabado",
        imagen:"3.jpg",
        grados:10,
        clima:"lluvioso"
    },
    {
        id:7,
        dia:"Domingo",
        imagen:"4.jpg",
        grados:7,
        clima:"tormenta"
    },
];

export let ListaClimaMet:Array<Climareg>=[
    {
        id:1,
        dia:"Lunes",
        imagen:"1.png",
        grados:10,
        clima:"soleado"
    },
    {
        id:2,
        dia:"Martes",
        imagen:"3.jpg",
        grados:10,
        clima:"lluvioso"
    },
    {
        id:3,
        dia:"Miercoles",
        imagen:"2.jpg",
        grados:15,
        clima:"nublado"
    },
    {
        id:4,
        dia:"Jueves",
        imagen:"4.jpg",
        grados:7,
        clima:"tormenta"
    },
    {
        id:5,
        dia:"Viernes",
        imagen:"1.png",
        grados:25,
        clima:"soleado"
    },
    {
        id:6,
        dia:"Sabado",
        imagen:"1.png",
        grados:18,
        clima:"soleado"
    },
    {
        id:7,
        dia:"Domingo",
        imagen:"1.png",
        grados:15,
        clima:"soleado"
    },
];

export let ListaClimaBio:Array<Climareg>=[
    {
        id:1,
        dia:"Lunes",
        imagen:"2.jpg",
        grados:10,
        clima:"nublado"
    },
    {
        id:2,
        dia:"Martes",
        imagen:"3.jpg",
        grados:11,
        clima:"lluvioso"
    },
    {
        id:3,
        dia:"Miercoles",
        imagen:"4.jpg",
        grados:7,
        clima:"tormenta"
    },
    {
        id:4,
        dia:"Jueves",
        imagen:"3.jpg",
        grados:9,
        clima:"lluvioso"
    },
    {
        id:5,
        dia:"Viernes",
        imagen:"2.jpg",
        grados:11,
        clima:"nublado"
    },
    {
        id:6,
        dia:"Sabado",
        imagen:"1.png",
        grados:12,
        clima:"soleado"
    },
    {
        id:7,
        dia:"Domingo",
        imagen:"1.png",
        grados:15,
        clima:"soleado"
    },
];

export let ListaClimaAra:Array<Climareg>=[
    {
        id:1,
        dia:"Lunes",
        imagen:"3.jpg",
        grados:10,
        clima:"lluvioso"
    },
    {
        id:2,
        dia:"Martes",
        imagen:"3.jpg",
        grados:10,
        clima:"lluvioso"
    },
    {
        id:3,
        dia:"Miercoles",
        imagen:"3.jpg",
        grados:7,
        clima:"lluvioso"
    },
    {
        id:4,
        dia:"Jueves",
        imagen:"4.jpg",
        grados:5,
        clima:"tormenta"
    },
    {
        id:5,
        dia:"Viernes",
        imagen:"4.jpg",
        grados:8,
        clima:"tormenta"
    },
    {
        id:6,
        dia:"Sabado",
        imagen:"3.jpg",
        grados:5,
        clima:"lluvioso"
    },
    {
        id:7,
        dia:"Domingo",
        imagen:"4.jpg",
        grados:6,
        clima:"tormenta"
    },
];